b = [
    {
        "name": "2011 Volkswagen Golf 90TSI Trendline VI Auto MY11",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 52799,
        "list_type": "dealer",
        "price": 12800,
    },
    {
        "name": "2013 Volkswagen Golf 103TSI Highline 7 Auto",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 69372,
        "list_type": "private",
        "price": 17500,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 48470,
        "list_type": "dealer",
        "price": 18990,
    },
    {
        "name": "2009 Volkswagen Golf 103TDI Comfortline VI Auto",
        "year": 2009,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 149692,
        "list_type": "private",
        "price": 8900,
    },
    {
        "name": "2011 Volkswagen Golf 118TSI VI Manual MY12",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 54033,
        "list_type": "dealer",
        "price": 17990,
    },
    {
        "name": "2019 Volkswagen Golf 110TSI Trendline 7.5 Auto MY19.5",
        "year": 2019,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 10500,
        "list_type": "private",
        "price": 22000,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 42277,
        "list_type": "dealer",
        "price": 23490,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 48470,
        "list_type": "dealer",
        "price": 18990,
    },
    {
        "name": "2016 Volkswagen Golf R 7 Auto 4MOTION MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 110658,
        "list_type": "dealer",
        "price": 31990,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 48500,
        "list_type": "private",
        "price": 26000,
    },
    {
        "name": "2011 Volkswagen Golf 118TSI VI Manual MY12",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 54033,
        "list_type": "dealer",
        "price": 17990,
    },
    {
        "name": "2011 Volkswagen Golf 90TSI Trendline VI Auto MY11",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 52799,
        "list_type": "dealer",
        "price": 12800,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 42277,
        "list_type": "dealer",
        "price": 23490,
    },
    {
        "name": "2016 Volkswagen Golf GTI 7 Auto MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 48241,
        "list_type": "dealer",
        "price": 32990,
    },
    {
        "name": "2011 Volkswagen Golf GTI VI Manual MY11",
        "year": 2011,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 81700,
        "list_type": "private",
        "price": 17750,
    },
    {
        "name": "2012 Volkswagen Golf 90TSI Trendline VI Manual MY12.5",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 135366,
        "list_type": "dealer",
        "price": 9888,
    },
    {
        "name": "2009 Volkswagen Golf 103TDI Comfortline VI Auto",
        "year": 2009,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 149692,
        "list_type": "private",
        "price": 8900,
    },
    {
        "name": "2013 Volkswagen Golf 103TSI Highline 7 Auto",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 69372,
        "list_type": "private",
        "price": 17500,
    },
    {
        "name": "2019 Volkswagen Golf 110TSI Trendline 7.5 Auto MY19.5",
        "year": 2019,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 10500,
        "list_type": "private",
        "price": 22000,
    },
    {
        "name": "2014 Volkswagen Golf GTI 7 Manual MY14",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 97000,
        "list_type": "private",
        "price": 24000,
    },
    {
        "name": "2019 Volkswagen Golf GTI 7.5 Auto MY19.5",
        "year": 2019,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 12689,
        "list_type": "dealer",
        "price": 47888,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 93590,
        "list_type": "dealer",
        "price": 22990,
    },
    {
        "name": "2004 Volkswagen Golf Comfortline V Manual",
        "year": 2004,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 175000,
        "list_type": "dealer",
        "price": 4888,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 89375,
        "list_type": "dealer",
        "price": 19988,
    },
    {
        "name": "2012 Volkswagen Golf GTI VI Auto MY13",
        "year": 2012,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 32489,
        "list_type": "dealer",
        "price": 27990,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI 7 Auto",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 142356,
        "list_type": "dealer",
        "price": 11850,
    },
    {
        "name": "2008 Volkswagen Golf Comfortline V Auto MY08",
        "year": 2008,
        "engineSize": 1.9,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 115729,
        "list_type": "dealer",
        "price": 7990,
    },
    {
        "name": "2016 Volkswagen Golf R 7 Auto 4MOTION MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 10754,
        "list_type": "private",
        "price": 39495,
    },
    {
        "name": "2014 Volkswagen Golf 103TSI Highline 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 94746,
        "list_type": "private",
        "price": 16990,
    },
    {
        "name": "2013 Volkswagen Golf 110TDI Highline 7 Auto",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 164000,
        "list_type": "dealer",
        "price": 13990,
    },
    {
        "name": "2019 Volkswagen Golf 110TSI Trendline 7.5 Auto MY19.5",
        "year": 2019,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 10961,
        "list_type": "dealer",
        "price": 25990,
    },
    {
        "name": "2015 Volkswagen Golf 103TSI Highline 7 Auto MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 77952,
        "list_type": "dealer",
        "price": 18990,
    },
    {
        "name": "2015 Volkswagen Golf 90TSI 7 Manual MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 95012,
        "list_type": "private",
        "price": 11450,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 132329,
        "list_type": "dealer",
        "price": 13927,
    },
    {
        "name": "2018 Volkswagen Golf Alltrack 132TSI Premium 7.5 Auto 4MOTION MY18",
        "year": 2018,
        "engineSize": 1.8,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 44119,
        "list_type": "private",
        "price": 33000,
    },
    {
        "name": "2015 Volkswagen Golf 90TSI Comfortline 7 Auto MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 63072,
        "list_type": "dealer",
        "price": 16990,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI Comfortline 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 39821,
        "list_type": "dealer",
        "price": 17980,
    },
    {
        "name": "2011 Volkswagen Golf R VI Manual 4MOTION MY11",
        "year": 2011,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 48000,
        "list_type": "private",
        "price": 26000,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Trendline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 88300,
        "list_type": "dealer",
        "price": 18990,
    },
    {
        "name": "2012 Volkswagen Golf GTI VI Auto MY12.5",
        "year": 2012,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 118055,
        "list_type": "dealer",
        "price": 18963,
    },
    {
        "name": "2008 Volkswagen Golf GTI V Auto MY08",
        "year": 2008,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 151000,
        "list_type": "dealer",
        "price": 11990,
    },
    {
        "name": "2008 Volkswagen Golf Pacific V Manual MY09",
        "year": 2008,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 190010,
        "list_type": "private",
        "price": 6900,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 67920,
        "list_type": "private",
        "price": 19300,
    },
    {
        "name": "2013 Volkswagen Golf 110TDI Highline 7 Auto MY14",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 58557,
        "list_type": "private",
        "price": 18500,
    },
    {
        "name": "2013 Volkswagen Golf 118TSI VI Auto MY13.5",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 85657,
        "list_type": "private",
        "price": 18000,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI Comfortline 7 Auto MY15",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 34648,
        "list_type": "dealer",
        "price": 18990,
    },
    {
        "name": "2015 Volkswagen Golf 90TSI 7 Auto MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 52000,
        "list_type": "private",
        "price": 15500,
    },
    {
        "name": "2016 Volkswagen Golf R 7 Auto 4MOTION MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 52291,
        "list_type": "private",
        "price": 38000,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI Comfortline 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 68463,
        "list_type": "dealer",
        "price": 16990,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Highline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 44867,
        "list_type": "dealer",
        "price": 31950,
    },
    {
        "name": "2017 Volkswagen Golf R 7 Manual 4MOTION MY17",
        "year": 2017,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 78524,
        "list_type": "dealer",
        "price": 38888,
    },
    {
        "name": "2012 Volkswagen Golf 118TSI VI Auto MY13",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 85800,
        "list_type": "dealer",
        "price": 15880,
    },
    {
        "name": "2012 Volkswagen Golf 118TSI Comfortline VI Auto MY13",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 77413,
        "list_type": "dealer",
        "price": 13770,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 40450,
        "list_type": "dealer",
        "price": 22870,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Auto 4MOTION MY14",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 86000,
        "list_type": "private",
        "price": 44000,
    },
    {
        "name": "2018 Volkswagen Golf R 7.5 Auto 4MOTION MY19",
        "year": 2018,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 38446,
        "list_type": "private",
        "price": 47500,
    },
    {
        "name": "2019 Volkswagen Golf GTI 7.5 Auto MY19.5",
        "year": 2019,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 6000,
        "list_type": "private",
        "price": 44990,
    },
    {
        "name": "2019 Volkswagen Golf R 7.5 Auto 4MOTION MY19.5",
        "year": 2019,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 12456,
        "list_type": "dealer",
        "price": 56987,
    },
    {
        "name": "2014 Volkswagen Golf 103TSI Highline 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 99167,
        "list_type": "dealer",
        "price": 16550,
    },
    {
        "name": "2010 Volkswagen Golf 118TSI Comfortline VI Auto MY11",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 94000,
        "list_type": "private",
        "price": 12250,
    },
    {
        "name": "2015 Volkswagen Golf 92TSI Comfortline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 44680,
        "list_type": "dealer",
        "price": 17990,
    },
    {
        "name": "2015 Volkswagen Golf R 7 Auto 4MOTION MY16",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 41500,
        "list_type": "private",
        "price": 41950,
    },
    {
        "name": "2012 Volkswagen Golf 118TSI Comfortline VI Auto MY13",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 88286,
        "list_type": "private",
        "price": 11000,
    },
    {
        "name": "2013 Volkswagen Golf 103TSI Highline 7 Auto MY14",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 100500,
        "list_type": "private",
        "price": 16500,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 69189,
        "list_type": "private",
        "price": 23300,
    },
    {
        "name": "2011 Volkswagen Golf 118TSI Comfortline VI Auto MY12",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 134000,
        "list_type": "private",
        "price": 10500,
    },
    {
        "name": "2015 Volkswagen Golf GTI Performance 7 Auto MY15",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 69390,
        "list_type": "private",
        "price": 31800,
    },
    {
        "name": "2015 Volkswagen Golf 110TDI Highline 7 Auto MY15",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 70000,
        "list_type": "private",
        "price": 20000,
    },
    {
        "name": "2006 Volkswagen Golf GTI V Auto MY07",
        "year": 2006,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 76749,
        "list_type": "private",
        "price": 14999,
    },
    {
        "name": "2014 Volkswagen Golf 118TSI VI Auto MY15",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 111000,
        "list_type": "private",
        "price": 13490,
    },
    {
        "name": "2009 Volkswagen Golf 118TSI Comfortline VI Auto",
        "year": 2009,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 135427,
        "list_type": "private",
        "price": 9699,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Trendline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 37061,
        "list_type": "private",
        "price": 20000,
    },
    {
        "name": "2012 Volkswagen Golf GTD VI Auto MY12.5",
        "year": 2012,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 149137,
        "list_type": "private",
        "price": 13500,
    },
    {
        "name": "2012 Volkswagen Golf GTI VI Manual MY12.5",
        "year": 2012,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 116667,
        "list_type": "dealer",
        "price": 18488,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 26000,
        "list_type": "private",
        "price": 26000,
    },
    {
        "name": "1995 Volkswagen Golf Manual",
        "year": 1995,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 270000,
        "list_type": "private",
        "price": 14500,
    },
    {
        "name": "2010 Volkswagen Golf R VI Auto 4MOTION MY11",
        "year": 2010,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 73000,
        "list_type": "private",
        "price": 26000,
    },
    {
        "name": "2012 Volkswagen Golf GTI VI Auto MY12.5",
        "year": 2012,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 72791,
        "list_type": "private",
        "price": 22000,
    },
    {
        "name": "2010 Volkswagen Golf 90TSI Trendline VI Auto MY10",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 158000,
        "list_type": "private",
        "price": 8000,
    },
    {
        "name": "2012 Volkswagen Golf 118TSI Comfortline VI Auto MY13",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 44000,
        "list_type": "private",
        "price": 14000,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Auto 4MOTION MY15",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 83000,
        "list_type": "private",
        "price": 31500,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Trendline 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 35000,
        "list_type": "private",
        "price": 19500,
    },
    {
        "name": "2011 Volkswagen Golf GTI Edition 35 VI Auto MY12",
        "year": 2011,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 90000,
        "list_type": "private",
        "price": 21000,
    },
    {
        "name": "2012 Volkswagen Golf GTI VI Auto MY13",
        "year": 2012,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 103000,
        "list_type": "private",
        "price": 22000,
    },
    {
        "name": "2011 Volkswagen Golf 118TSI VI Manual MY12",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 120000,
        "list_type": "private",
        "price": 10000,
    },
    {
        "name": "2009 Volkswagen Golf 118TSI Comfortline VI Auto",
        "year": 2009,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 120000,
        "list_type": "private",
        "price": 9000,
    },
    {
        "name": "2007 Volkswagen Golf Comfortline V Auto MY08",
        "year": 2007,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 132829,
        "list_type": "private",
        "price": 9299,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Comfortline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 65000,
        "list_type": "private",
        "price": 19500,
    },
    {
        "name": "2015 Volkswagen Golf 90TSI 7 Auto MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 45000,
        "list_type": "private",
        "price": 16400,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 36000,
        "list_type": "private",
        "price": 23000,
    },
    {
        "name": "2010 Volkswagen Golf 118TSI Comfortline VI Auto MY10",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 193000,
        "list_type": "private",
        "price": 7990,
    },
    {
        "name": "2012 Volkswagen Golf 77TSI VI Manual MY12.5",
        "year": 2012,
        "engineSize": 1.2,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 103000,
        "list_type": "private",
        "price": 8500,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Highline 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 29000,
        "list_type": "private",
        "price": 27990,
    },
    {
        "name": "2015 Volkswagen Golf 90TSI Comfortline 7 Auto MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 30497,
        "list_type": "private",
        "price": 16990,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI Comfortline 7 Auto MY14",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 146000,
        "list_type": "private",
        "price": 10800,
    },
    {
        "name": "2010 Volkswagen Golf GTI VI Manual MY10",
        "year": 2010,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 186000,
        "list_type": "private",
        "price": 13500,
    },
    {
        "name": "2015 Volkswagen Golf R 7 Auto 4MOTION MY15",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 102040,
        "list_type": "dealer",
        "price": 31800,
    },
    {
        "name": "2014 Volkswagen Golf GTI Performance 7 Auto MY15",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 90000,
        "list_type": "private",
        "price": 29999,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Auto 4MOTION MY15",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 54900,
        "list_type": "private",
        "price": 31995,
    },
    {
        "name": "2009 Volkswagen Golf Edition V Auto MY09",
        "year": 2009,
        "engineSize": 1.9,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 192000,
        "list_type": "private",
        "price": 8950,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 78900,
        "list_type": "private",
        "price": 24800,
    },
    {
        "name": "2016 Volkswagen Golf R 7 Auto 4MOTION MY17",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 80000,
        "list_type": "private",
        "price": 34000,
    },
    {
        "name": "2012 Volkswagen Golf 118TSI Comfortline VI Auto MY12.5",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 112000,
        "list_type": "private",
        "price": 10000,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Trendline 7 Manual MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 70000,
        "list_type": "private",
        "price": 16500,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Auto 4MOTION MY15",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 39400,
        "list_type": "private",
        "price": 33500,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI 7 Auto MY15",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 98000,
        "list_type": "private",
        "price": 13000,
    },
    {
        "name": "2018 Volkswagen Golf R 7.5 Auto 4MOTION MY19",
        "year": 2018,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 21498,
        "list_type": "private",
        "price": 47900,
    },
    {
        "name": "2013 Volkswagen Golf 103TDI Comfortline VI Auto MY13.5",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 139493,
        "list_type": "private",
        "price": 12000,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI 7 Auto",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 58900,
        "list_type": "private",
        "price": 12999,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI 7.5 Manual MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 105000,
        "list_type": "private",
        "price": 13000,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Auto 4MOTION MY14",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 110000,
        "list_type": "private",
        "price": 32000,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Trendline 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 56000,
        "list_type": "private",
        "price": 19990,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI Comfortline 7 Auto MY15",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 59085,
        "list_type": "private",
        "price": 15999,
    },
    {
        "name": "2014 Volkswagen Golf 110TDI Highline 7 Auto MY14",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 182157,
        "list_type": "private",
        "price": 14850,
    },
    {
        "name": "2006 Volkswagen Golf Comfortline V Auto MY07",
        "year": 2006,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 77426,
        "list_type": "dealer",
        "price": 9490,
    },
    {
        "name": "2011 Volkswagen Golf R VI Auto 4MOTION MY11",
        "year": 2011,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 147000,
        "list_type": "private",
        "price": 22999,
    },
    {
        "name": "2015 Volkswagen Golf 92TSI 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 102045,
        "list_type": "dealer",
        "price": 14490,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Trendline 7.5 Manual MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 75596,
        "list_type": "dealer",
        "price": 26990,
    },
    {
        "name": "2010 Volkswagen Golf GTI VI Manual MY11",
        "year": 2010,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 136000,
        "list_type": "private",
        "price": 18000,
    },
    {
        "name": "2009 Volkswagen Golf 103TDI Comfortline VI Auto MY10",
        "year": 2009,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 203858,
        "list_type": "private",
        "price": 7750,
    },
    {
        "name": "2017 Volkswagen Golf GTI 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 20440,
        "list_type": "private",
        "price": 34500,
    },
    {
        "name": "2018 Volkswagen Golf GTI 7.5 Auto MY19",
        "year": 2018,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 7800,
        "list_type": "private",
        "price": 45800,
    },
    {
        "name": "2013 Volkswagen Golf 110TDI Highline 7 Auto",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 56581,
        "list_type": "dealer",
        "price": 19839,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Comfortline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 42941,
        "list_type": "private",
        "price": 17500,
    },
    {
        "name": "2007 Volkswagen Golf GTI V Auto MY07",
        "year": 2007,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 197561,
        "list_type": "dealer",
        "price": 10999,
    },
    {
        "name": "2009 Volkswagen Golf 90TSI Trendline VI Auto MY10",
        "year": 2009,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 92509,
        "list_type": "private",
        "price": 9999,
    },
    {
        "name": "2009 Volkswagen Golf 103TDI Comfortline VI Auto",
        "year": 2009,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 195415,
        "list_type": "dealer",
        "price": 8299,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 64919,
        "list_type": "dealer",
        "price": 22999,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Trendline 7.5 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 71363,
        "list_type": "dealer",
        "price": 19990,
    },
    {
        "name": "2015 Volkswagen Golf 90TSI 7 Auto MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 79697,
        "list_type": "dealer",
        "price": 15990,
    },
    {
        "name": "2005 Volkswagen Golf Comfortline V Auto",
        "year": 2005,
        "engineSize": 1.9,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 200778,
        "list_type": "dealer",
        "price": 4999,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI 7 Manual MY15",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 82841,
        "list_type": "private",
        "price": 11950,
    },
    {
        "name": "2006 Volkswagen Golf Comfortline V Auto",
        "year": 2006,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 204565,
        "list_type": "dealer",
        "price": 5888,
    },
    {
        "name": "2015 Volkswagen Golf 92TSI Trendline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 96738,
        "list_type": "dealer",
        "price": 14850,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Trendline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 113604,
        "list_type": "dealer",
        "price": 17890,
    },
    {
        "name": "2014 Volkswagen Golf 103TSI Highline 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 53480,
        "list_type": "dealer",
        "price": 19990,
    },
    {
        "name": "2012 Volkswagen Golf 118TSI VI Auto MY12",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 76537,
        "list_type": "dealer",
        "price": 15975,
    },
    {
        "name": "2010 Volkswagen Golf 103TDI Comfortline VI Auto MY10",
        "year": 2010,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 162835,
        "list_type": "dealer",
        "price": 9488,
    },
    {
        "name": "2006 Volkswagen Golf Comfortline V Manual",
        "year": 2006,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 134745,
        "list_type": "dealer",
        "price": 6500,
    },
    {
        "name": "2015 Volkswagen Golf 110TDI Highline 7 Auto MY16",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 125691,
        "list_type": "dealer",
        "price": 17990,
    },
    {
        "name": "2008 Volkswagen Golf Pacific V Auto MY08",
        "year": 2008,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 128420,
        "list_type": "dealer",
        "price": 10999,
    },
    {
        "name": "2004 Volkswagen Golf Generation 4th Gen Auto MY04",
        "year": 2004,
        "engineSize": 1.6,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 164446,
        "list_type": "dealer",
        "price": 7999,
    },
    {
        "name": "2005 Volkswagen Golf Comfortline V Auto",
        "year": 2005,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 209574,
        "list_type": "dealer",
        "price": 5250,
    },
    {
        "name": "2006 Volkswagen Golf Comfortline V Manual",
        "year": 2006,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 159942,
        "list_type": "dealer",
        "price": 6998,
    },
    {
        "name": "2005 Volkswagen Golf Trendline V Auto",
        "year": 2005,
        "engineSize": 1.6,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 208894,
        "list_type": "dealer",
        "price": 5299,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Trendline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 7430,
        "list_type": "private",
        "price": 20000,
    },
    {
        "name": "2006 Volkswagen Golf GTI V Manual",
        "year": 2006,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 140118,
        "list_type": "dealer",
        "price": 12999,
    },
    {
        "name": "2015 Volkswagen Golf 103TSI Highline 7 Auto MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 102425,
        "list_type": "dealer",
        "price": 21880,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Comfortline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 134301,
        "list_type": "dealer",
        "price": 13999,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI Trendline VI Auto MY13.5",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 132722,
        "list_type": "dealer",
        "price": 13888,
    },
    {
        "name": "2004 Volkswagen Golf Generation 4th Gen Manual MY04",
        "year": 2004,
        "engineSize": 1.6,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 117200,
        "list_type": "private",
        "price": 6500,
    },
    {
        "name": "2019 Volkswagen Golf R 7.5 Auto 4MOTION MY19.5",
        "year": 2019,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 13452,
        "list_type": "private",
        "price": 52500,
    },
    {
        "name": "2012 Volkswagen Golf 90TSI 7 Manual",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 120771,
        "list_type": "dealer",
        "price": 10990,
    },
    {
        "name": "2019 Volkswagen Golf 110TSI Highline 7.5 Auto MY19.5",
        "year": 2019,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 12524,
        "list_type": "dealer",
        "price": 39800,
    },
    {
        "name": "2016 Volkswagen Golf 110TDI Highline 7 Auto MY17",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 75515,
        "list_type": "dealer",
        "price": 23990,
    },
    {
        "name": "2015 Volkswagen Golf R Wolfsburg Edition 7 Auto 4MOTION MY16",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 130001,
        "list_type": "dealer",
        "price": 33950,
    },
    {
        "name": "2011 Volkswagen Golf 77TSI VI Auto MY11",
        "year": 2011,
        "engineSize": 1.2,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 110300,
        "list_type": "dealer",
        "price": 10950,
    },
    {
        "name": "2011 Volkswagen Golf GTI VI Manual MY11",
        "year": 2011,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 65264,
        "list_type": "private",
        "price": 19000,
    },
    {
        "name": "2015 Volkswagen Golf R Wolfsburg Edition 7 Auto 4MOTION MY16",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 39000,
        "list_type": "private",
        "price": 39990,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Manual 4MOTION MY15",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 96581,
        "list_type": "dealer",
        "price": 34999,
    },
    {
        "name": "2013 Volkswagen Golf 118TSI Comfortline VI Auto MY13.5",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 145181,
        "list_type": "dealer",
        "price": 12990,
    },
    {
        "name": "2016 Volkswagen Golf GTI 7 Manual MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 111490,
        "list_type": "dealer",
        "price": 28950,
    },
    {
        "name": "2007 Volkswagen Golf Comfortline V Manual MY07",
        "year": 2007,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 178443,
        "list_type": "private",
        "price": 5500,
    },
    {
        "name": "2006 Volkswagen Golf Comfortline V Manual",
        "year": 2006,
        "engineSize": 1.6,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 274893,
        "list_type": "dealer",
        "price": 3999,
    },
    {
        "name": "2017 Volkswagen Golf R 7 Auto 4MOTION MY17",
        "year": 2017,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 45133,
        "list_type": "dealer",
        "price": 40990,
    },
    {
        "name": "2012 Volkswagen Golf 118TSI VI Auto MY12",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 81133,
        "list_type": "private",
        "price": 13700,
    },
    {
        "name": "2011 Volkswagen Golf 118TSI Comfortline VI Auto MY12",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 145000,
        "list_type": "private",
        "price": 9500,
    },
    {
        "name": "2015 Volkswagen Golf 110TDI Highline 7 Auto MY15",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 162316,
        "list_type": "dealer",
        "price": 13990,
    },
    {
        "name": "2006 Volkswagen Golf GTI V Manual",
        "year": 2006,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 286400,
        "list_type": "private",
        "price": 7500,
    },
    {
        "name": "2016 Volkswagen Golf GTI 7 Auto MY17",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 64054,
        "list_type": "dealer",
        "price": 30950,
    },
    {
        "name": "2010 Volkswagen Golf 118TSI Comfortline VI Auto MY10",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 161069,
        "list_type": "dealer",
        "price": 8999,
    },
    {
        "name": "2002 Volkswagen Golf SE 4th Gen Auto MY02",
        "year": 2002,
        "engineSize": 1.6,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 144615,
        "list_type": "dealer",
        "price": 6498,
    },
    {
        "name": "2013 Volkswagen Golf 103TDI Comfortline VI Auto MY13.5",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 72605,
        "list_type": "dealer",
        "price": 15990,
    },
    {
        "name": "2015 Volkswagen Golf 110TSI Highline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 51057,
        "list_type": "dealer",
        "price": 20990,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 74032,
        "list_type": "dealer",
        "price": 18980,
    },
    {
        "name": "2011 Volkswagen Golf 118TSI Comfortline VI Auto MY11",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 142747,
        "list_type": "private",
        "price": 10000,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI Comfortline 7 Auto MY14",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 105690,
        "list_type": "dealer",
        "price": 14990,
    },
    {
        "name": "2003 Volkswagen Golf S 4th Gen Manual MY02",
        "year": 2003,
        "engineSize": 1.6,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 148200,
        "list_type": "dealer",
        "price": 4990,
    },
    {
        "name": "2013 Volkswagen Golf 103TSI Highline 7 Auto",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 53769,
        "list_type": "dealer",
        "price": 16888,
    },
    {
        "name": "2010 Volkswagen Golf 103TDI Comfortline VI Auto MY10",
        "year": 2010,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 112147,
        "list_type": "dealer",
        "price": 7888,
    },
    {
        "name": "2013 Volkswagen Golf 103TDI Comfortline VI Auto MY13.5",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 150521,
        "list_type": "dealer",
        "price": 11999,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Highline 7 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 180024,
        "list_type": "dealer",
        "price": 15990,
    },
    {
        "name": "2017 Volkswagen Golf GTI 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 21944,
        "list_type": "dealer",
        "price": 35990,
    },
    {
        "name": "2014 Volkswagen Golf 110TDI Highline 7 Auto MY14",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 39926,
        "list_type": "dealer",
        "price": 22990,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 141672,
        "list_type": "dealer",
        "price": 13999,
    },
    {
        "name": "2009 Volkswagen Golf 118TSI Comfortline VI Auto MY10",
        "year": 2009,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 125712,
        "list_type": "dealer",
        "price": 8499,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Auto 4MOTION MY14",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 110000,
        "list_type": "private",
        "price": 26000,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI 7 Auto MY14",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 124732,
        "list_type": "dealer",
        "price": 12990,
    },
    {
        "name": "2017 Volkswagen Golf Alltrack 135TDI Premium 7.5 Auto 4MOTION MY17",
        "year": 2017,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 27696,
        "list_type": "dealer",
        "price": 31500,
    },
    {
        "name": "2011 Volkswagen Golf GTI VI Auto MY11",
        "year": 2011,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 114800,
        "list_type": "dealer",
        "price": 16688,
    },
    {
        "name": "2009 Volkswagen Golf 103TDI Comfortline VI Manual",
        "year": 2009,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 176500,
        "list_type": "private",
        "price": 7000,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 56139,
        "list_type": "dealer",
        "price": 23990,
    },
    {
        "name": "2010 Volkswagen Golf 118TSI Comfortline VI Auto MY11",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 141704,
        "list_type": "dealer",
        "price": 9990,
    },
    {
        "name": "2009 Volkswagen Golf 90TSI Trendline VI Auto",
        "year": 2009,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 100707,
        "list_type": "dealer",
        "price": 9499,
    },
    {
        "name": "2013 Volkswagen Golf 103TSI Highline 7 Auto MY14",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 110250,
        "list_type": "private",
        "price": 14800,
    },
    {
        "name": "2013 Volkswagen Golf 103TDI Comfortline VI Auto MY13.5",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 126725,
        "list_type": "dealer",
        "price": 13990,
    },
    {
        "name": "2011 Volkswagen Golf 90TSI Trendline VI Auto MY12",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 86731,
        "list_type": "private",
        "price": 9999,
    },
    {
        "name": "2014 Volkswagen Golf 110TDI Highline 7 Auto MY14",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 139851,
        "list_type": "dealer",
        "price": 15497,
    },
    {
        "name": "2011 Volkswagen Golf 90TSI Trendline VI Auto MY11",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 110539,
        "list_type": "dealer",
        "price": 9990,
    },
    {
        "name": "2011 Volkswagen Golf 90TSI Trendline VI Auto MY11",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 79859,
        "list_type": "dealer",
        "price": 14999,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 13509,
        "list_type": "dealer",
        "price": 23950,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 97809,
        "list_type": "dealer",
        "price": 15990,
    },
    {
        "name": "2011 Volkswagen Golf 118TSI VI Auto MY12",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 150952,
        "list_type": "dealer",
        "price": 13990,
    },
    {
        "name": "2018 Volkswagen Golf GTI 7.5 Manual MY18",
        "year": 2018,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 15000,
        "list_type": "private",
        "price": 46500,
    },
    {
        "name": "2015 Volkswagen Golf 92TSI Comfortline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 43660,
        "list_type": "dealer",
        "price": 20990,
    },
    {
        "name": "2015 Volkswagen Golf 90TSI Comfortline 7 Auto MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 122258,
        "list_type": "dealer",
        "price": 15990,
    },
    {
        "name": "2012 Volkswagen Golf 77TSI VI Auto MY12.5",
        "year": 2012,
        "engineSize": 1.2,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 91455,
        "list_type": "dealer",
        "price": 11990,
    },
    {
        "name": "2015 Volkswagen Golf R Wolfsburg Edition 7 Auto 4MOTION MY16",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 45000,
        "list_type": "private",
        "price": 42000,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 44441,
        "list_type": "private",
        "price": 21000,
    },
    {
        "name": "2013 Volkswagen Golf 110TDI Highline 7 Auto MY14",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 118000,
        "list_type": "dealer",
        "price": 14999,
    },
    {
        "name": "2015 Volkswagen Golf 110TSI Highline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 210459,
        "list_type": "private",
        "price": 10900,
    },
    {
        "name": "2014 Volkswagen Golf 103TSI Highline 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 199145,
        "list_type": "dealer",
        "price": 9990,
    },
    {
        "name": "2015 Volkswagen Golf 92TSI Comfortline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 100299,
        "list_type": "dealer",
        "price": 18890,
    },
    {
        "name": "2012 Volkswagen Golf 118TSI VI Auto MY12",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 125000,
        "list_type": "private",
        "price": 12990,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI Comfortline 7 Auto MY15",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 106336,
        "list_type": "dealer",
        "price": 17990,
    },
    {
        "name": "2016 Volkswagen Golf Alltrack 132TSI 7 Auto 4MOTION MY17",
        "year": 2016,
        "engineSize": 1.8,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 42230,
        "list_type": "dealer",
        "price": 26851,
    },
    {
        "name": "2010 Volkswagen Golf GTI VI Auto MY11",
        "year": 2010,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 137029,
        "list_type": "dealer",
        "price": 18888,
    },
    {
        "name": "2008 Volkswagen Golf GT Sport V Auto MY08",
        "year": 2008,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 178000,
        "list_type": "dealer",
        "price": 8499,
    },
    {
        "name": "2017 Volkswagen Golf R 7 Auto 4MOTION MY17",
        "year": 2017,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 45000,
        "list_type": "private",
        "price": 39000,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Highline 7 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 41450,
        "list_type": "dealer",
        "price": 24890,
    },
    {
        "name": "2016 Volkswagen Golf Alltrack 132TSI 7 Auto 4MOTION MY16",
        "year": 2016,
        "engineSize": 1.8,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 110886,
        "list_type": "dealer",
        "price": 20989,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Trendline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 53229,
        "list_type": "dealer",
        "price": 18880,
    },
    {
        "name": "2003 Volkswagen Golf Sport 4th Gen Auto MY03",
        "year": 2003,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 221114,
        "list_type": "dealer",
        "price": 4999,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Highline 7.5 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 33981,
        "list_type": "private",
        "price": 28500,
    },
    {
        "name": "2015 Volkswagen Golf 92TSI Trendline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 33297,
        "list_type": "dealer",
        "price": 21990,
    },
    {
        "name": "2015 Volkswagen Golf 110TDI Highline 7 Auto MY15",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 70998,
        "list_type": "dealer",
        "price": 20990,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 78641,
        "list_type": "dealer",
        "price": 22436,
    },
    {
        "name": "2017 Volkswagen Golf 92TSI Trendline 7 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 110092,
        "list_type": "dealer",
        "price": 17990,
    },
    {
        "name": "2007 Volkswagen Golf GT Sport V Auto MY08",
        "year": 2007,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 177023,
        "list_type": "dealer",
        "price": 7700,
    },
    {
        "name": "2014 Volkswagen Golf GTI 7 Auto MY14",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 99000,
        "list_type": "private",
        "price": 23490,
    },
    {
        "name": "2010 Volkswagen Golf 90TSI Trendline VI Auto MY11",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 38000,
        "list_type": "private",
        "price": 15000,
    },
    {
        "name": "2013 Volkswagen Golf 110TDI Highline 7 Auto",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 94047,
        "list_type": "dealer",
        "price": 14888,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Comfortline 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 95382,
        "list_type": "dealer",
        "price": 16950,
    },
    {
        "name": "2010 Volkswagen Golf 118TSI Comfortline VI Auto MY11",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 143780,
        "list_type": "private",
        "price": 8950,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Auto 4MOTION MY15",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 96243,
        "list_type": "private",
        "price": 29990,
    },
    {
        "name": "2015 Volkswagen Golf GTI 7 Auto MY16",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 82000,
        "list_type": "private",
        "price": 28499,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 64609,
        "list_type": "dealer",
        "price": 19990,
    },
    {
        "name": "2015 Volkswagen Golf 110TSI Highline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 105981,
        "list_type": "dealer",
        "price": 16550,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI Comfortline 7 Auto MY14",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 81000,
        "list_type": "private",
        "price": 14999,
    },
    {
        "name": "2017 Volkswagen Golf 92TSI Comfortline 7 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 79219,
        "list_type": "dealer",
        "price": 22990,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI 7.5 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 86759,
        "list_type": "dealer",
        "price": 20888,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 103000,
        "list_type": "dealer",
        "price": 18890,
    },
    {
        "name": "2017 Volkswagen Golf 92TSI Trendline 7 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 106296,
        "list_type": "dealer",
        "price": 16688,
    },
    {
        "name": "2019 Volkswagen Golf R 7.5 Auto 4MOTION MY20",
        "year": 2019,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 15392,
        "list_type": "dealer",
        "price": 51990,
    },
    {
        "name": "2015 Volkswagen Golf GTI 7 Auto MY15",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 66524,
        "list_type": "dealer",
        "price": 28888,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 30445,
        "list_type": "dealer",
        "price": 26990,
    },
    {
        "name": "2012 Volkswagen Golf GTI VI Auto MY12.5",
        "year": 2012,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 140000,
        "list_type": "private",
        "price": 22990,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Comfortline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 47100,
        "list_type": "private",
        "price": 17490,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Trendline 7.5 Manual MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 47227,
        "list_type": "dealer",
        "price": 21990,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Trendline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 73051,
        "list_type": "dealer",
        "price": 14998,
    },
    {
        "name": "2017 Volkswagen Golf GTI Performance Edition 1 7.5 Auto MY17",
        "year": 2017,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 38000,
        "list_type": "private",
        "price": 36000,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI Comfortline 7 Manual",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 66000,
        "list_type": "private",
        "price": 13400,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 157341,
        "list_type": "dealer",
        "price": 14946,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Trendline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 19200,
        "list_type": "private",
        "price": 21999,
    },
    {
        "name": "2015 Volkswagen Golf 92TSI Comfortline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 52541,
        "list_type": "dealer",
        "price": 19990,
    },
    {
        "name": "2000 Volkswagen Golf GL 4th Gen Auto",
        "year": 2000,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 243838,
        "list_type": "dealer",
        "price": 4499,
    },
    {
        "name": "2005 Volkswagen Golf Trendline V Manual",
        "year": 2005,
        "engineSize": 1.6,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 208503,
        "list_type": "dealer",
        "price": 4499,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Highline 7 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 26000,
        "list_type": "private",
        "price": 27500,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 80521,
        "list_type": "dealer",
        "price": 15990,
    },
    {
        "name": "2010 Volkswagen Golf 118TSI Comfortline VI Auto MY11",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 160000,
        "list_type": "private",
        "price": 6990,
    },
    {
        "name": "2005 Volkswagen Golf Comfortline V Auto",
        "year": 2005,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 153655,
        "list_type": "dealer",
        "price": 6499,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 64078,
        "list_type": "dealer",
        "price": 21990,
    },
    {
        "name": "2010 Volkswagen Golf 103TDI Comfortline VI Auto MY11",
        "year": 2010,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 177144,
        "list_type": "dealer",
        "price": 8950,
    },
    {
        "name": "2013 Volkswagen Golf 110TDI Highline 7 Auto MY14",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 83077,
        "list_type": "dealer",
        "price": 18990,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 54000,
        "list_type": "private",
        "price": 18499,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI Comfortline 7 Manual",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 78469,
        "list_type": "dealer",
        "price": 14890,
    },
    {
        "name": "2011 Volkswagen Golf 90TSI Trendline VI Auto MY11",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 84798,
        "list_type": "dealer",
        "price": 11999,
    },
    {
        "name": "2010 Volkswagen Golf 118TSI Comfortline VI Manual MY10",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 111558,
        "list_type": "dealer",
        "price": 10850,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Trendline 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 31600,
        "list_type": "dealer",
        "price": 20888,
    },
    {
        "name": "2019 Volkswagen Golf GTI 7.5 Auto MY19.5",
        "year": 2019,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 12500,
        "list_type": "dealer",
        "price": 46500,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Auto 4MOTION MY15",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 168880,
        "list_type": "private",
        "price": 27500,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Trendline 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 63001,
        "list_type": "dealer",
        "price": 20490,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Comfortline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 62664,
        "list_type": "private",
        "price": 18200,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 39760,
        "list_type": "dealer",
        "price": 23990,
    },
    {
        "name": "2012 Volkswagen Golf 118TSI VI Auto MY12",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 87799,
        "list_type": "private",
        "price": 15500,
    },
    {
        "name": "2013 Volkswagen Golf 103TSI Highline 7 Auto MY14",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 138000,
        "list_type": "private",
        "price": 11500,
    },
    {
        "name": "2019 Volkswagen Golf R 7.5 Auto 4MOTION MY20",
        "year": 2019,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 12063,
        "list_type": "dealer",
        "price": 53990,
    },
    {
        "name": "2016 Volkswagen Golf GTI 7 Manual MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 121000,
        "list_type": "dealer",
        "price": 25888,
    },
    {
        "name": "2013 Volkswagen Golf 103TSI Highline 7 Auto MY14",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 103000,
        "list_type": "private",
        "price": 16500,
    },
    {
        "name": "2015 Volkswagen Golf GTI 7 Auto MY15",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 68000,
        "list_type": "private",
        "price": 27500,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Trendline 7.5 Manual MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 86030,
        "list_type": "dealer",
        "price": 16990,
    },
    {
        "name": "2007 Volkswagen Golf Comfortline V Auto MY08",
        "year": 2007,
        "engineSize": 1.6,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 124200,
        "list_type": "private",
        "price": 14500,
    },
    {
        "name": "2012 Volkswagen Golf 90TSI Trendline VI Manual MY13",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 191000,
        "list_type": "private",
        "price": 9000,
    },
    {
        "name": "2016 Volkswagen Golf 110TDI Highline 7 Auto MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 38483,
        "list_type": "private",
        "price": 19900,
    },
    {
        "name": "2010 Volkswagen Golf 118TSI Comfortline VI Auto MY10",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 140702,
        "list_type": "private",
        "price": 9000,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 29178,
        "list_type": "dealer",
        "price": 24990,
    },
    {
        "name": "2007 Volkswagen Golf Comfortline V Auto MY07",
        "year": 2007,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 150666,
        "list_type": "dealer",
        "price": 7990,
    },
    {
        "name": "2015 Volkswagen Golf 92TSI Comfortline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 22420,
        "list_type": "private",
        "price": 19280,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Trendline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 83367,
        "list_type": "dealer",
        "price": 17890,
    },
    {
        "name": "2011 Volkswagen Golf 77TSI VI Auto MY12",
        "year": 2011,
        "engineSize": 1.2,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 105817,
        "list_type": "private",
        "price": 10500,
    },
    {
        "name": "2013 Volkswagen Golf 103TSI Highline 7 Auto",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 113309,
        "list_type": "dealer",
        "price": 17550,
    },
    {
        "name": "2013 Volkswagen Golf 110TDI Highline 7 Auto",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 80346,
        "list_type": "dealer",
        "price": 15888,
    },
    {
        "name": "2011 Volkswagen Golf 118TSI Comfortline VI Auto MY12",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 92515,
        "list_type": "private",
        "price": 12000,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 13188,
        "list_type": "dealer",
        "price": 21990,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI Comfortline 7 Auto MY15",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 29930,
        "list_type": "dealer",
        "price": 19990,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Comfortline 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 128393,
        "list_type": "dealer",
        "price": 14990,
    },
    {
        "name": "2018 Volkswagen Golf R 7.5 Auto 4MOTION MY19",
        "year": 2018,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 24250,
        "list_type": "private",
        "price": 49500,
    },
    {
        "name": "2018 Volkswagen Golf Alltrack 132TSI Premium 7.5 Auto 4MOTION MY18",
        "year": 2018,
        "engineSize": 1.8,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 73608,
        "list_type": "dealer",
        "price": 31987,
    },
    {
        "name": "2015 Volkswagen Golf 92TSI Trendline 7 Auto MY16",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 69712,
        "list_type": "dealer",
        "price": 19990,
    },
    {
        "name": "2019 Volkswagen Golf 110TSI Trendline 7.5 Auto MY20",
        "year": 2019,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 34000,
        "list_type": "private",
        "price": 23000,
    },
    {
        "name": "2014 Volkswagen Golf 103TSI Highline 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 50990,
        "list_type": "dealer",
        "price": 19890,
    },
    {
        "name": "2016 Volkswagen Golf R 7 Auto 4MOTION MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 82891,
        "list_type": "dealer",
        "price": 35990,
    },
    {
        "name": "2012 Volkswagen Golf 90TSI Trendline VI Auto MY13",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 95967,
        "list_type": "dealer",
        "price": 11990,
    },
    {
        "name": "2016 Volkswagen Golf R 7 Auto 4MOTION MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 73850,
        "list_type": "private",
        "price": 37500,
    },
    {
        "name": "2015 Volkswagen Golf GTI Performance 7 Auto MY16",
        "year": 2015,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 38335,
        "list_type": "dealer",
        "price": 33990,
    },
    {
        "name": "2017 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 41915,
        "list_type": "dealer",
        "price": 25890,
    },
    {
        "name": "2016 Volkswagen Golf GTI Performance 7 Auto MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 93279,
        "list_type": "dealer",
        "price": 29490,
    },
    {
        "name": "2008 Volkswagen Golf Edition V Manual MY08",
        "year": 2008,
        "engineSize": 1.9,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 186275,
        "list_type": "dealer",
        "price": 6499,
    },
    {
        "name": "2014 Volkswagen Golf 110TDI Highline 7 Auto MY14",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 83486,
        "list_type": "dealer",
        "price": 18990,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 126000,
        "list_type": "dealer",
        "price": 17900,
    },
    {
        "name": "2016 Volkswagen Golf 110TSI Highline 7 Auto MY16",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 93610,
        "list_type": "private",
        "price": 21500,
    },
    {
        "name": "2017 Volkswagen Golf 92TSI 7 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 35390,
        "list_type": "dealer",
        "price": 19990,
    },
    {
        "name": "2012 Volkswagen Golf 103TSI Highline 7 Auto",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 102386,
        "list_type": "dealer",
        "price": 16990,
    },
    {
        "name": "2017 Volkswagen Golf 92TSI Comfortline 7 Auto MY17",
        "year": 2017,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 104988,
        "list_type": "dealer",
        "price": 15888,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 120566,
        "list_type": "dealer",
        "price": 14397,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI Comfortline 7 Auto MY15",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 135600,
        "list_type": "dealer",
        "price": 13900,
    },
    {
        "name": "2008 Volkswagen Golf GTI V Manual MY08",
        "year": 2008,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 148570,
        "list_type": "dealer",
        "price": 13990,
    },
    {
        "name": "2011 Volkswagen Golf 90TSI Trendline VI Auto MY11",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 103010,
        "list_type": "private",
        "price": 9500,
    },
    {
        "name": "2016 Volkswagen Golf R 7 Manual 4MOTION MY17",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 60000,
        "list_type": "private",
        "price": 34500,
    },
    {
        "name": "2010 Volkswagen Golf 90TSI Trendline VI Auto MY10",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 91538,
        "list_type": "dealer",
        "price": 12950,
    },
    {
        "name": "2012 Volkswagen Golf 77TSI VI Auto MY12.5",
        "year": 2012,
        "engineSize": 1.2,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 113000,
        "list_type": "dealer",
        "price": 10449,
    },
    {
        "name": "2006 Volkswagen Golf Trendline V Auto MY07",
        "year": 2006,
        "engineSize": 1.9,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 141011,
        "list_type": "dealer",
        "price": 7998,
    },
    {
        "name": "2006 Volkswagen Golf GTI V Auto MY07",
        "year": 2006,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 168700,
        "list_type": "private",
        "price": 11000,
    },
    {
        "name": "2013 Volkswagen Golf 110TDI Highline 7 Auto",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 98000,
        "list_type": "private",
        "price": 15200,
    },
    {
        "name": "2016 Volkswagen Golf GTI 7 Auto MY16",
        "year": 2016,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 64600,
        "list_type": "private",
        "price": 29863,
    },
    {
        "name": "2012 Volkswagen Golf GTI VI Auto MY13",
        "year": 2012,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 159322,
        "list_type": "private",
        "price": 14800,
    },
    {
        "name": "2017 Volkswagen Golf R 7.5 Auto 4MOTION MY18",
        "year": 2017,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 41900,
        "list_type": "private",
        "price": 41600,
    },
    {
        "name": "2013 Volkswagen Golf GTI 7 Auto MY14",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 78000,
        "list_type": "private",
        "price": 24300,
    },
    {
        "name": "2011 Volkswagen Golf GTI VI Manual MY11",
        "year": 2011,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 118000,
        "list_type": "private",
        "price": 16500,
    },
    {
        "name": "2012 Volkswagen Golf GTI VI Auto MY13",
        "year": 2012,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 152000,
        "list_type": "private",
        "price": 15000,
    },
    {
        "name": "2008 Volkswagen Golf GT Sport V Manual MY08",
        "year": 2008,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 210000,
        "list_type": "private",
        "price": 7200,
    },
    {
        "name": "2007 Volkswagen Golf R32 V Auto 4MOTION MY07",
        "year": 2007,
        "engineSize": 3.2,
        "numberOfCylinder": 6,
        "fuelType": "Diesel",
        "odometer": 185500,
        "list_type": "private",
        "price": 14500,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Auto 4MOTION MY15",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 149000,
        "list_type": "private",
        "price": 26500,
    },
    {
        "name": "2010 Volkswagen Golf R VI Manual 4MOTION MY11",
        "year": 2010,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 159800,
        "list_type": "private",
        "price": 21500,
    },
    {
        "name": "2008 Volkswagen Golf Pacific V Auto MY09",
        "year": 2008,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 97000,
        "list_type": "private",
        "price": 9999,
    },
    {
        "name": "2008 Volkswagen Golf GTI V Auto MY09",
        "year": 2008,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 153861,
        "list_type": "private",
        "price": 10500,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI Comfortline 7 Auto",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 163000,
        "list_type": "dealer",
        "price": 9000,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Trendline 7.5 Auto MY19",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 34045,
        "list_type": "private",
        "price": 19500,
    },
    {
        "name": "2010 Volkswagen Golf 118TSI Comfortline VI Auto MY10",
        "year": 2010,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 159696,
        "list_type": "dealer",
        "price": 9995,
    },
    {
        "name": "2018 Volkswagen Golf 110TSI Comfortline 7.5 Auto MY18",
        "year": 2018,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 39672,
        "list_type": "dealer",
        "price": 23990,
    },
    {
        "name": "2013 Volkswagen Golf 90TSI 7 Auto",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 93274,
        "list_type": "private",
        "price": 12400,
    },
    {
        "name": "2005 Volkswagen Golf Trendline V Auto",
        "year": 2005,
        "engineSize": 1.6,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 193275,
        "list_type": "dealer",
        "price": 4499,
    },
    {
        "name": "2006 Volkswagen Golf GTI V Auto",
        "year": 2006,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 172000,
        "list_type": "private",
        "price": 9500,
    },
    {
        "name": "2017 Volkswagen Golf R 7 Auto 4MOTION MY17",
        "year": 2017,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 36000,
        "list_type": "private",
        "price": 47500,
    },
    {
        "name": "2015 Volkswagen Golf 103TSI Highline 7 Auto MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 43000,
        "list_type": "private",
        "price": 20000,
    },
    {
        "name": "2009 Volkswagen Golf 90TSI Trendline VI Auto",
        "year": 2009,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 145250,
        "list_type": "dealer",
        "price": 8899,
    },
    {
        "name": "2012 Volkswagen Golf 118TSI Comfortline VI Auto MY12.5",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 52905,
        "list_type": "dealer",
        "price": 15990,
    },
    {
        "name": "2013 Volkswagen Golf 103TSI Highline 7 Auto",
        "year": 2013,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 88800,
        "list_type": "private",
        "price": 14950,
    },
    {
        "name": "2008 Volkswagen Golf Pacific V Auto MY08",
        "year": 2008,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 202050,
        "list_type": "private",
        "price": 7000,
    },
    {
        "name": "2018 Volkswagen Golf R 7.5 Auto 4MOTION MY18",
        "year": 2018,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 30000,
        "list_type": "private",
        "price": 49995,
    },
    {
        "name": "2008 Volkswagen Golf GTI Pirelli V Auto MY09",
        "year": 2008,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 45000,
        "list_type": "private",
        "price": 20000,
    },
    {
        "name": "2015 Volkswagen Golf 90TSI 7 Manual MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 92000,
        "list_type": "private",
        "price": 13000,
    },
    {
        "name": "2015 Volkswagen Golf 103TSI Highline 7 Auto MY15",
        "year": 2015,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 98077,
        "list_type": "private",
        "price": 17950,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI Comfortline 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 52000,
        "list_type": "private",
        "price": 14950,
    },
    {
        "name": "2012 Volkswagen Golf 90TSI Trendline VI Auto MY12.5",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 140000,
        "list_type": "private",
        "price": 10500,
    },
    {
        "name": "2013 Volkswagen Golf GTI 7 Manual MY14",
        "year": 2013,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 94700,
        "list_type": "private",
        "price": 23500,
    },
    {
        "name": "2007 Volkswagen Golf GT Sport V Auto MY08",
        "year": 2007,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 119000,
        "list_type": "private",
        "price": 8000,
    },
    {
        "name": "2014 Volkswagen Golf 110TDI Highline 7 Auto MY14",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 128000,
        "list_type": "private",
        "price": 14999,
    },
    {
        "name": "2011 Volkswagen Golf 118TSI Comfortline VI Manual MY12",
        "year": 2011,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 108481,
        "list_type": "private",
        "price": 9000,
    },
    {
        "name": "2011 Volkswagen Golf GTI VI Auto MY12",
        "year": 2011,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 92000,
        "list_type": "private",
        "price": 18500,
    },
    {
        "name": "2014 Volkswagen Golf GTI 7 Auto MY15",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 63633,
        "list_type": "private",
        "price": 26500,
    },
    {
        "name": "2012 Volkswagen Golf 90TSI Trendline VI Auto MY12.5",
        "year": 2012,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 190608,
        "list_type": "private",
        "price": 8900,
    },
    {
        "name": "2014 Volkswagen Golf 90TSI Comfortline 7 Auto MY14",
        "year": 2014,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 86000,
        "list_type": "private",
        "price": 14000,
    },
    {
        "name": "2011 Volkswagen Golf GTI VI Manual MY11",
        "year": 2011,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 79000,
        "list_type": "private",
        "price": 17300,
    },
    {
        "name": "2014 Volkswagen Golf R 7 Auto 4MOTION MY15",
        "year": 2014,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 53000,
        "list_type": "private",
        "price": 33999,
    },
    {
        "name": "2016 Volkswagen Golf 92TSI Trendline 7 Auto MY17",
        "year": 2016,
        "engineSize": 1.4,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 110000,
        "list_type": "private",
        "price": 14990,
    },
    {
        "name": "2008 Volkswagen Golf Pacific V Auto MY08",
        "year": 2008,
        "engineSize": 2.0,
        "numberOfCylinder": 4,
        "fuelType": "Diesel",
        "odometer": 173907,
        "list_type": "private",
        "price": 7900,
    },
]
