[
    {
        "fineLine": "0011880",
        "displayName": "Ozito PXC 150mm 36 Tooth Circular Saw Blade",
        "productUrl": "/ozito-pxc-150mm-36-tooth-circular-saw-blade_p0011880",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Tool Accessories > Power Saw Blade & Accessories > Circular Saw Blades",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 12.95,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/b4bda8b6-6117-4ac5-8926-3d7a9d32d9b0.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0018372",
        "displayName": "Ozito PXC 18V 5.2Ah Ultra Battery",
        "productUrl": "/ozito-pxc-18v-5-2ah-ultra-battery_p0018372",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Batteries & Chargers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 99.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/c49a74a9-4fb2-4294-b657-0bd73b666a63.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 5},
    },
    {
        "fineLine": "0011879",
        "displayName": "Ozito PXC 150mm 18 Tooth Circular Saw Blade",
        "productUrl": "/ozito-pxc-150mm-18-tooth-circular-saw-blade_p0011879",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Tool Accessories > Power Saw Blade & Accessories > Circular Saw Blades",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 9.95,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/a57c0649-03b4-4f39-a2a6-8b2a52e590da.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": True,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0025615",
        "displayName": "Ozito PXC Sharpening Wheel",
        "productUrl": "/ozito-pxc-sharpening-wheel_p0025615",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Chainsaws > Chainsaws Parts & Accessories",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 14.98,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/70d285b9-7c0e-4b28-b103-e0005372507e.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0033141",
        "displayName": "Ozito PXC 18V 165mm Circular Saw - Skin Only",
        "productUrl": "/ozito-pxc-18v-165mm-circular-saw-skin-only_p0033141",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Power Saws > Cordless Saws",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 89.98,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/94096d83-b452-4a12-a9bc-0f5fe124cf72.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.7143, "totalReviewCount": 7},
    },
    {
        "fineLine": "0035838",
        "displayName": "Ozito PXC 18V Standard Charger",
        "productUrl": "/ozito-pxc-18v-standard-charger_p0035838",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Batteries & Chargers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 19.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/ce459ddf-1d77-44a8-b44f-170954cf46be.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.8, "totalReviewCount": 5},
    },
    {
        "fineLine": "0035840",
        "displayName": "Ozito PXC 18V Multi Battery Fast Charger",
        "productUrl": "/ozito-pxc-18v-multi-battery-fast-charger_p0035840",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Batteries & Chargers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 56.64,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/9a704b38-6420-4c12-bffe-dc83354efd74.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0035841",
        "displayName": "Ozito PXC 18V 210mm Compound Mitre Saw - Skin Only",
        "productUrl": "/ozito-pxc-18v-210mm-compound-mitre-saw-skin-only_p0035841",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Power Saws > Cordless Saws",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 109.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/bdef78c0-c353-4c50-94c5-48824e097023.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.5714, "totalReviewCount": 7},
    },
    {
        "fineLine": "0082358",
        "displayName": "Ozito PXC 2 x 18V Cordless Line Trimmer Kit",
        "productUrl": "/ozito-pxc-2-x-18v-cordless-line-trimmer-kit_p0082358",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Whipper Snippers & Line Trimmers > Cordless Whipper Snippers & Line Trimmers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 229.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/df6e2f7c-3f11-4572-b57b-80f200b73a9b.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.8, "totalReviewCount": 5},
    },
    {
        "fineLine": "0085438",
        "displayName": "Ozito PXC 18V 125mm Brushless Angle Grinder - Skin Only",
        "productUrl": "/ozito-pxc-18v-125mm-brushless-angle-grinder-skin-only_p0085438",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Grinders > Angle Grinder Skins",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 109.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/3446a4af-706e-4959-855b-c49240bd41ed.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 2.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0085439",
        "displayName": "Ozito PXC 18V Brushless Rotary Hammer Drill",
        "productUrl": "/ozito-pxc-18v-brushless-rotary-hammer-drill_p0085439",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Drills > Cordless Drill Skins",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 179.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/9c6fce4b-be52-4522-93a6-c1b309acc465.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0085440",
        "displayName": "Ozito PXC 18V Impact Driver Kit",
        "productUrl": "/ozito-pxc-18v-impact-driver-kit_p0085440",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Drills > Impact Drill Drivers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 99.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/565cfd37-cbda-4302-afdc-68198710961c.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": True,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 3.0, "totalReviewCount": 2},
    },
    {
        "fineLine": "0097195",
        "displayName": "Ozito PXC 18V Garden Sprayer - Skin Only",
        "productUrl": "/ozito-pxc-18v-garden-sprayer-skin-only_p0097195",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Pressure Washers > Cordless Pressure Washers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 75.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/5e3a756a-4dd8-468e-b495-3eb00d7c250c.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.5, "totalReviewCount": 4},
    },
    {
        "fineLine": "0098552",
        "displayName": "Ozito PXC 18V Compact Multi Function Tool - Skin Only",
        "productUrl": "/ozito-pxc-18v-compact-multi-function-tool-skin-only_p0098552",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Multi Tools > Multi Tool Skins",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 59.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/9b63a377-6227-409a-8bdb-4fe8ada43b67.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 3.6667, "totalReviewCount": 3},
    },
    {
        "fineLine": "0109216",
        "displayName": "Ozito PXC 18V Cordless Lawn Edger - Skin Only",
        "productUrl": "/ozito-pxc-18v-cordless-lawn-edger-skin-only_p0109216",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Garden Edgers > Cordless Edgers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 149.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/d0466711-7e3a-48ef-a769-133ef1e0f7a1.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0119784",
        "displayName": "Ozito PXC 18V Chainsaw And Sharpening Kit",
        "productUrl": "/ozito-pxc-18v-chainsaw-and-sharpening-kit_p0119784",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Chainsaws > Cordless Chainsaws",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 199.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/60ab43d3-c2c9-4e22-96c7-67a7e283d8ec.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0123306",
        "displayName": "Ozito PXC 18V Variable Speed Blower Kit",
        "productUrl": "/ozito-pxc-18v-variable-speed-blower-kit_p0123306",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Blower Vac & Leaf Blowers > Cordless Blower Vac & Leaf Blowers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 165.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/51329bae-6d72-4068-a2b0-d3f40a6405ec.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0123310",
        "displayName": "Ozito PXC 18V Brushless Lawn Mower - Skin Only",
        "productUrl": "/ozito-pxc-18v-brushless-lawn-mower-skin-only_p0123310",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Lawn Mowers > Cordless Lawn Mowers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 169.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/080f118b-d88a-4d2f-b204-69d6cd9907ae.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.6, "totalReviewCount": 10},
    },
    {
        "fineLine": "0124074",
        "displayName": "Ozito PXC 18V Drill Driver - Skin Only",
        "productUrl": "/ozito-pxc-18v-drill-driver-skin-only_p0124074",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Drills > Cordless Drill Skins",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 39.98,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/dc996628-e8d8-4543-ba63-4cd45e0acd8b.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 3.0, "totalReviewCount": 3},
    },
    {
        "fineLine": "0124076",
        "displayName": "Ozito PXC 18V Hammer Drill - Skin Only",
        "productUrl": "/ozito-pxc-18v-hammer-drill-skin-only_p0124076",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Drills > Hammer Drills",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 49.98,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/99502540-c1ff-480a-bc12-dc48763d8a84.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0124077",
        "displayName": "Ozito PXC 18V Drill Driver Kit",
        "productUrl": "/ozito-pxc-18v-drill-driver-kit_p0124077",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Drills > Cordless Power Tool & Drill Kits",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 99.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/4f0d5a38-8d85-46e7-9fac-3f8cf0ed7813.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.5, "totalReviewCount": 8},
    },
    {
        "fineLine": "0128938",
        "displayName": "Ozito PXC 18V Cordless Outdoor Paint Spray Gun - Skin Only",
        "productUrl": "/ozito-pxc-18v-cordless-outdoor-paint-spray-gun-skin-only_p0128938",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Paint & Decorating > Paint Accessories > Power Painting",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 69.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/163dba25-011b-4d74-af7b-b5fdce228b12.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0134396",
        "displayName": "Ozito PXC 18V Seed And Fertiliser Spreader - Skin Only",
        "productUrl": "/ozito-pxc-18v-seed-and-fertiliser-spreader-skin-only_p0134396",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Power Saws > Cordless Saws",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 55.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/00294efc-e294-4cd3-9451-3039403c5a23.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0136008",
        "displayName": "Ozito PXC 18V 2 In 1 Cordless Nail And Staple Gun - Skin Only",
        "productUrl": "/ozito-pxc-18v-2-in-1-cordless-nail-and-staple-gun-skin-only_p0136008",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Nail, Glue & Heat Guns > Nail Gun Skins",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 109.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/7c08d582-2d81-477f-a908-b49adca668e0.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 3.6667, "totalReviewCount": 3},
    },
    {
        "fineLine": "0128940",
        "displayName": "Ozito PXC 18V 10L Cordless Wet And Dry Vacuum / Inflator - Skin Only",
        "productUrl": "/ozito-pxc-18v-10l-cordless-wet-and-dry-vacuum-inflator-skin-only_p0128940",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Workshop Vacuums > Cordless Vacuums",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 79.98,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/34e3bcda-dcf2-4d57-be1f-d923d52683c4.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": True,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0136009",
        "displayName": "Ozito PXC 18V Cordless Staple Gun - Skin Only",
        "productUrl": "/ozito-pxc-18v-cordless-staple-gun-skin-only_p0136009",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 79.98,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/cc0d8a8d-16fd-4b46-8a35-0dbe94ed4242.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0136010",
        "displayName": "Ozito PXC 18V Hybrid Twin LED Worklights And Tripod - Skin Only",
        "productUrl": "/ozito-pxc-18v-hybrid-twin-led-worklights-and-tripod-skin-only_p0136010",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Worklights",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 99.99,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/588ab82a-7703-4592-9d71-aaf4337c44e6.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0136011",
        "displayName": "Ozito PXC 18V Cordless LED Worklight - Skin Only",
        "productUrl": "/ozito-pxc-18v-cordless-led-worklight-skin-only_p0136011",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Worklights",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 39.99,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/c482a634-b893-46a0-a562-2953c0315617.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 2},
    },
    {
        "fineLine": "0136012",
        "displayName": "Ozito PXC 18V Brushless 2 In 1 Sander And Polisher - Skin Only",
        "productUrl": "/ozito-pxc-18v-brushless-2-in-1-sander-and-polisher-skin-only_p0136012",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Sanders > Sander Skins",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 159.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/468a510a-0bb0-4132-b2f4-3ab7c5e904fd.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0136013",
        "displayName": "Ozito PXC 11mm 18V Cordless Glue Gun - Skin Only",
        "productUrl": "/ozito-pxc-11mm-18v-cordless-glue-gun-skin-only_p0136013",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Nail, Glue & Heat Guns > Hot Glue Guns",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 39.98,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/d2a6c03f-ef9c-448b-bd03-8dc6e3ef883e.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.6667, "totalReviewCount": 3},
    },
    {
        "fineLine": "0136014",
        "displayName": "Ozito PXC 10L Vacuum Bags",
        "productUrl": "/ozito-pxc-10l-vacuum-bags_p0136014",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Workshop Vacuums > Vacuum Cleaner Parts & Accessories",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 12.98,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": True,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/872c64e8-4526-4b3d-8357-bf505af68969.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": False,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0136015",
        "displayName": "Ozito PXC 18V Hammer Drill Kit",
        "productUrl": "/ozito-pxc-18v-hammer-drill-kit_p0136015",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Drills > Cordless Power Tool & Drill Kits",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 129.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/9c8e6344-450f-43c2-8214-fc483d7a12cc.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 4.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0163609",
        "displayName": "Ozito PXC 18V Cordless Compact Jigsaw - Skin Only",
        "productUrl": "/ozito-pxc-18v-cordless-compact-jigsaw-skin-only_p0163609",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 49.98,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/ab5e3997-bb2b-4401-b3df-95ab97e9e5fa.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0163610",
        "displayName": "Ozito PXC Power X Chance 18V Hybrid Fan - Skin Only",
        "productUrl": "/ozito-pxc-power-x-chance-18v-hybrid-fan-skin-only_p0163610",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Cordless Fans & Blowers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 59.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/bb05423d-1a04-415f-a7aa-9eb3e06b87d7.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": True,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 2},
    },
    {
        "fineLine": "0163612",
        "displayName": "Ozito PXC 18V Cordless Multi Mixer - Skin Only",
        "productUrl": "/ozito-pxc-18v-cordless-multi-mixer-skin-only_p0163612",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 119.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/2f7583f4-982a-43de-99d8-fdb2c1c6a62e.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0163616",
        "displayName": "Ozito PXC 18V Cordless Heat Gun - Skin Only",
        "productUrl": "/ozito-pxc-18v-cordless-heat-gun-skin-only_p0163616",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Nail, Glue & Heat Guns > Heat Guns",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 79.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/a6b81b92-0144-42b1-b461-589228e2c84e.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 2},
    },
    {
        "fineLine": "0167718",
        "displayName": "Ozito PXC 18V Cylinder Lawn Mower - Skin Only",
        "productUrl": "/ozito-pxc-18v-cylinder-lawn-mower-skin-only_p0167718",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Lawn Mowers > Cordless Lawn Mowers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 160.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/fa201964-6bb6-4bdb-8e78-04f9fe0c6b65.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 3.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0167719",
        "displayName": "Ozito PXC 2 x 18V Cordless Line Trimmer - Skin Only",
        "productUrl": "/ozito-pxc-2-x-18v-cordless-line-trimmer-skin-only_p0167719",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Whipper Snippers & Line Trimmers > Cordless Whipper Snippers & Line Trimmers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 145.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/cbec8342-7ba5-4df4-9c23-7f0ff9b1e42a.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 3.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0179976",
        "displayName": "Ozito PXC 2 x 18V Cordless Hedge Trimmer - Skin",
        "productUrl": "/ozito-pxc-2-x-18v-cordless-hedge-trimmer-skin_p0179976",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Whipper Snippers & Line Trimmers > Cordless Whipper Snippers & Line Trimmers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 149.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/d9b247e6-4aef-4aba-b670-0937141c9cc2.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 2},
    },
    {
        "fineLine": "0195625",
        "displayName": "Ozito Power X Change 18V Cordless Bluetooth Speaker - Skin Only",
        "productUrl": "/ozito-power-x-change-18v-cordless-bluetooth-speaker-skin-only_p0195625",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 35.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/8a5b1b97-c8b0-4820-9a0c-7ca078339da6.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0195859",
        "displayName": "Ozito Power X Change 18V Compact Drill And Impact Driver Kit",
        "productUrl": "/ozito-power-x-change-18v-compact-drill-and-impact-driver-kit_p0195859",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 99.98,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/cd774f7b-965e-4779-8e7d-5c9bb18357ef.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0195861",
        "displayName": "Ozito Power X Change 18V 2.5Ah Battery And Charger Pack",
        "productUrl": "/ozito-power-x-change-18v-2-5ah-battery-and-charger-pack_p0195861",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 59.99,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/0f6846a5-49b5-4aea-88e9-e64039a40fcc.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0203456",
        "displayName": "Ozito PXC 2 x 18V 3 In 1 Blower Vacuum-Mulcher Kit",
        "productUrl": "/ozito-pxc-2-x-18v-3-in-1-blower-vacuum-mulcher-kit_p0203456",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Blower Vac & Leaf Blowers > Cordless Blower Vac & Leaf Blowers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 199.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/ede92aca-157a-4cdf-8266-a27392619579.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0203457",
        "displayName": "Ozito PXC 18V Grass Trimmer And Hedge Trimmer Kit",
        "productUrl": "/ozito-pxc-18v-grass-trimmer-and-hedge-trimmer-kit_p0203457",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Drills > Cordless Power Tool & Drill Kits",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 149.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/908d4042-5227-41e1-96c1-3646e1c64c7d.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0203458",
        "displayName": "Ozito PXC 18V Grass Trimmer Kit",
        "productUrl": "/ozito-pxc-18v-grass-trimmer-kit_p0203458",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Garden > Garden Tools > Whipper Snippers & Line Trimmers > Cordless Whipper Snippers & Line Trimmers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 79.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/cd33e933-fac5-46b2-a68c-d7a573da73a4.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 1.0, "totalReviewCount": 1},
    },
    {
        "fineLine": "0203459",
        "displayName": "Ozito PXC 18V Blower, Grass Trimmer And Hedge Trimmer Kit",
        "productUrl": "/ozito-pxc-18v-blower-grass-trimmer-and-hedge-trimmer-kit_p0203459",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Drills > Cordless Power Tool & Drill Kits",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 199.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/ac65b4ab-6d96-47a6-b12d-c89e8f7f8237.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 0.0, "totalReviewCount": 0},
    },
    {
        "fineLine": "0203460",
        "displayName": "Ozito PXC Ultimate Cordless Garden Care Kit",
        "productUrl": "/ozito-pxc-ultimate-cordless-garden-care-kit_p0203460",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Drills > Cordless Power Tool & Drill Kits",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 399.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/910299be-8cf8-4978-aad6-e2d09059ebfc.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 2},
    },
    {
        "fineLine": "0203461",
        "displayName": "Ozito PXC 18V 7.5L Garden Sprayer Kit",
        "productUrl": "/ozito-pxc-18v-7-5l-garden-sprayer-kit_p0203461",
        "brandName": "Ozito PXC",
        "brandLogo": "https://media.bunnings.com.au/Brand-62x40/b2f0af98-7e20-4ef9-a3f4-75274dcf3f73.png",
        "categoryNamePath": "Our Range > Tools > Power Tools > Pressure Washers > Cordless Pressure Washers",
        "forHire": False,
        "unitOfMeasure": "Each",
        "price": 99.0,
        "hasComparisonPrice": False,
        "comparisonPriceUnits": 0.0,
        "comparisonPriceUom": "",
        "isSpecialOrder": False,
        "availableForOrderOnline": True,
        "availableForPickUp": True,
        "availableForDelivery": True,
        "isTradingRestricted": False,
        "isThirdParty": False,
        "isBundle": False,
        "isCustomMade": False,
        "hasPOADelivery": False,
        "productImage": "https://media.bunnings.com.au/Product-190x190/7ea69872-44fc-462d-ade3-cab6055ecf31.jpg",
        "checkStoreForPrice": False,
        "stockStatus": None,
        "isFeatured": False,
        "sellerName": "",
        "isMarketplaceProduct": False,
        "showStockLevel": True,
        "isInStore": True,
        "productRatings": {"averageOverallRating": 5.0, "totalReviewCount": 1},
    },
]
